### ISSUE TITLE
[Thiếu API] - Giỏ hàng chưa có

### ISSUE THREAD

**Issue by ThaiTuan123** [ThaiTuan123/mocdecor#118]
<img width="816" alt="image" src="https://github.com/user-attachments/assets/6766db1f-0b11-4330-b1d5-d606c2fc6258">

**Comment by NgoKhanh03** [comment]
@ThaiTuan123 API Giỏ hàng: [API Giỏ hàng](https://api.mocdecor.org/api#/%5BPublic%5D%20Cart/CartController_findOne)
