### ISSUE TITLE
[Thiếu API] - Thông tin đơn hàng hiện tại chưa có API

### ISSUE THREAD

**Issue by ThaiTuan123** [ThaiTuan123/mocdecor#119]
<img width="527" alt="image" src="https://github.com/user-attachments/assets/08b0cd11-8173-42f8-b2d4-1e4dd54b5a8c">

cần bổ sung api thông tin đơn hàng

**Comment by NgoKhanh03** [comment]
> curl -X 'GET' \
  'https://api.mocdecor.org/cart/12345' \
  -H 'accept: */*'

**Comment by NgoKhanh03** [comment]
curl -X 'GET' \
  'https://api.mocdecor.org/cart/{browserId}' \
  -H 'accept: */*'

**Comment by NgoKhanh03** [comment]
API: [Mộc API](https://api.mocdecor.org/api#/%5BPublic%5D%20Cart/CartController_findOne)
